# Generated by Django 4.2.4 on 2023-08-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerService', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='BordingTime',
            new_name='bording_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='LandingTime',
            new_name='landing_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='travile_time',
            new_name='traveile_time',
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='CustomerService.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='CustomerService.airport'),
        ),
    ]
