# Generated by Django 4.2.4 on 2023-08-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='NationalId',
        ),
    ]
