# Generated by Django 4.2.4 on 2023-08-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_remove_customer_nationalid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CUSTOMER',
        ),
    ]
