# Generated by Django 4.2.4 on 2023-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='NationalId',
            field=models.CharField(default='', max_length=30),
        ),
    ]
