# Generated by Django 4.2.4 on 2023-08-10 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='number',
        ),
        migrations.AddField(
            model_name='flight',
            name='BordingTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='LandingTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='flight',
            name='travile_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to', to='customerService.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Depature', to='customerService.airport'),
        ),
    ]
