# Generated by Django 4.2.4 on 2023-08-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0003_contactform_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerService.login'),
        ),
    ]
