# Generated by Django 4.2.4 on 2023-08-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0004_alter_passenger_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='username',
        ),
    ]
