# Generated by Django 4.2.4 on 2023-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0005_remove_passenger_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='username',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
