# Generated by Django 4.2.4 on 2023-08-12 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0006_passenger_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('NationalId', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RoundFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roundduration', models.FloatField(default=6.0)),
                ('Roundtravil_date', models.DateField(default=datetime.datetime.now)),
                ('RoundBordingTime', models.FloatField(default=0)),
                ('RoundLandingTime', models.FloatField(default=0)),
                ('ReturnRoundBordingTime', models.FloatField(default=0)),
                ('ReturnRoundLandingTime', models.FloatField(default=0)),
                ('RoundPrice', models.IntegerField(default=0)),
                ('ReturnRounddestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoundReturnto', to='customerService.airport')),
                ('ReturnRoundorigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoundReturnDepature', to='customerService.airport')),
                ('Rounddestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roundto', to='customerService.airport')),
                ('Roundorigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoundDepature', to='customerService.airport')),
            ],
        ),
    ]
