# Generated by Django 4.2.4 on 2023-08-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundflight',
            old_name='BordingTime',
            new_name='ReturnRoundBordingTime',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='LandingTime',
            new_name='ReturnRoundLandingTime',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='Returndestination',
            new_name='ReturnRounddestination',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='Returnorigen',
            new_name='ReturnRoundorigen',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='Price',
            new_name='RoundPrice',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='destination',
            new_name='Rounddestination',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='duration',
            new_name='Roundduration',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='origen',
            new_name='Roundorigen',
        ),
        migrations.RenameField(
            model_name='roundflight',
            old_name='travile_time',
            new_name='Roundtravil_date',
        ),
        migrations.AddField(
            model_name='roundflight',
            name='RoundBordingTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roundflight',
            name='RoundLandingTime',
            field=models.FloatField(default=0),
        ),
    ]
